/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;

public class App {
        edu.princeton.cs.algs4.Draw draw;
        public App() {
            this.draw = new Draw();
            Grade grade = new Grade();
            this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            this.draw.setCanvasSize(1000,600);
            this.draw.setXscale(0,1000);
            this.draw.setYscale(0,600);
            grade.desenhar(this.draw);
            // Ajusta o tamanho da tela usando algum método do objeto Draw
            // Ajusta a escala X usando algum outro método do objeto Draw
            // Ajusta a escala Y usando ainda outro método do objeto Draw
        }

        public static void main(String[] args) {
            App app = new App();
            app.draw.show();

        }


}
